apiVersion: v1
kind: Service
metadata:
  name: {{ include "furiosa-metric-exporter.name" . }}
  namespace: {{ .Values.namespace | default "kube-system" }}
  labels:
    app.kubernetes.io/name: {{ include "furiosa-metric-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "metrics"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "furiosa-metric-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
