{
 "title": "NPU Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(furiosa_npu_alive,hostname)"
    }
   },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(furiosa_npu_alive,device)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(furiosa_npu_alive,pod)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(furiosa_npu_alive,namespace)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(furiosa_npu_alive,container)"
    }
   },
   {
    "name": "core",
    "query": {
     "query": "label_values(furiosa_npu_core_utilization,core)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Npu Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n  irate(furiosa_npu_task_execution_cycle{hostname=~\"${hostname}\", device=~\"${device}\", core=~\"${core}\", pod=~\"${pod}\", namespace=~\"${namespace}\", container=~\"${container}\"}[3m])\n  /\n  irate(furiosa_npu_total_cycle_count{hostname=~\"${hostname}\", device=~\"${device}\", core=~\"${core}\", pod=~\"${pod}\", namespace=~\"${namespace}\", container=~\"${container}\"}[3m])\n) * 100",
     "legendFormat": "{{hostname}}-{{namespace}}-{{pod}}-{{container}}: {{device}}:{{core}}"
    }
   ]
  },
  {
   "title": "Device Healthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "furiosa_npu_alive{hostname=~\"${hostname}\", device=~\"${device}\", pod=~\"${pod}\", namespace=~\"${namespace}\", container=~\"${container}\"}",
     "legendFormat": "{{hostname}}-{{namespace}}-{{pod}}-{{container}}: {{device}}"
    }
   ]
  },
  {
   "title": "Core Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "furiosa_npu_core_frequency{hostname=~\"${hostname}\", device=~\"${device}\", core=~\"${core}\", pod=~\"${pod}\", namespace=~\"${namespace}\", container=~\"${container}\"}",
     "legendFormat": "{{hostname}}-{{namespace}}-{{pod}}-{{container}}: {{device}}:{{core}}"
    }
   ]
  },
  {
   "title": "NPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (hostname, device, pod, namespace, container) (furiosa_npu_hw_temperature{hostname=~\"${hostname}\", device=~\"${device}\", pod=~\"${pod}\", namespace=~\"${namespace}\", container=~\"${container}\"})",
     "legendFormat": "{{hostname}}-{{namespace}}-{{pod}}-{{container}}: {{device}}"
    }
   ]
  },
  {
   "title": "Device Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "furiosa_npu_hw_power{hostname=~\"${hostname}\", device=~\"${device}\", pod=~\"${pod}\", namespace=~\"${namespace}\", container=~\"${container}\"}",
     "legendFormat": "{{hostname}}-{{namespace}}-{{pod}}-{{container}}: {{device}}"
    }
   ]
  }
 ]
}