name: Build & Push PR Image

on:
  pull_request:
    branches:
      - '*'

jobs:
  public_build_push:
    runs-on: "ubuntu-latest"
    env:
      PUBLIC_REGISTRY_URL: "registry.corp.furiosa.ai"
      PUBLIC_IMAGE_NAME: "furiosa/furiosa-metrics-exporter"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: docker/setup-buildx-action@v3
      - name: public registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.PUBLIC_REGISTRY_URL }}
          username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
          password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}
      - name: Build and publish PR image with SHA
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: '${{ env.PUBLIC_REGISTRY_URL }}/${{ env.PUBLIC_IMAGE_NAME }}:${{ github.event.pull_request.head.sha }}'
