name: Golang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.6' ]

    steps:
      - name: checkout furiosa-smi
        uses: actions/checkout@v4
        with:
          repository: furiosa-ai/furiosa-smi
          token: ${{ secrets.TOKEN_FOR_CLONE_ANOTHER_REPO}}
          # FIXME(@hoony9x): Due to breaking change from https://github.com/furiosa-ai/furiosa-smi/pull/89, we need to deal with this change too.
          # It must be handled in the next PR immediately.
          ref: c618316a701c6db23827a72fa09c67abd39dbfdf
          path: furiosa-smi
      - name: install furiosa-smi
        run: |
          cd furiosa-smi
          rustup component add clippy rustfmt
          cargo build
          make install
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: build
        run: make build
      - name: test
        run: make test
      - name: install golangci
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: lint
        run: make lint
